steps:
  # Install dependencies and deploy the agent
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Install and Deploy"
    entrypoint: "bash"
    args:
      - -c
      - |
        # The Makefile handles uv installation and dependency management.
        # The gcloud-sdk image has Python pre-installed.
        make install
        make deploy
    env:
      # These substitutions are passed to 'make deploy'
      - "PROJECT_ID=${_PROJECT_ID}"
      - "REGION=${_REGION}"

substitutions:
  _REGION: "us-east4"

options:
  logging: CLOUD_LOGGING_ONLY